---
- name: Ensure UFW is installed
  ansible.builtin.package:
    name: ufw
    state: latest
  when: ansible_distribution == 'Debian'

- name: Ensure UFW is started
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes
  tags:
    - firewall
  
- name: Ensure Firewall is enabled
  community.general.ufw:
    state: enabled
  tags:
    - firewall

- name: Open firewall ports tcp
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop: "{{ fw_ports_tcp }}"

- name: Open firewall ports udp
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: udp
  loop: "{{ fw_ports_udp }}"
